### ISSUE TITLE
Publish binary releases

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/SymphonyElectron#376]
In lieu of a fix for issue #278, can the project team please publish binary releases of SymphonyElectron, perhaps using [GitHub's releases mechanism](https://help.github.com/articles/creating-releases/)?

**Comment by pmonks** [comment]
@lneir Issue #278 is outside @VishwasShashidhar and @VikasShashidhar's control, as the root cause is in libffi / node.js.

In the meantime, it would be beneficial if the team were to share developmental builds of SymphonyElectron (assuming they themselves are successfully doing so), to allow those of us who are unable to build it ourselves to continue using the software.

**Comment by lneir** [comment]
it looks like the fix as been merged for ffi?  @VikasShashidhar @VishwasShashidhar what is our status for picking this up and getting #278 resolved?

**Comment by pmonks** [comment]
Yeah the fix was merged, but it hasn't been released yet (in fact that project hasn't had any releases in ~2 years).

**Comment by VishwasShashidhar** [comment]
@lneir yes, it's still not released, I'll follow up with the author and see if we can get something out.

@pmonks We are creating builds. Let me get back to you on publishing the releases here.
